# Generated by Django 3.2.3 on 2021-05-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210508_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
